server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gseek
    username: gseek
    password: gseek
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 7000


logging:
  level:
    root: debug
