server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gseek
    username: gseek
    password: gseek
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      # redis服务器地址
      host: 127.0.0.1
      database: 0
      port: 7000

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: gseek
  secretKey: gseek
  bucketName: gseek




logging:
  level:
    root: info

# 自定义参数
custom:
  # aes加密key值，在PasswordUtil#init中用到
  encryptKey: "test1encrypt2key"

