server:
  port: 8000

spring:

  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/gseek
    username: gseek
    password: gseek
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      # redis服务器地址
      host: 127.0.0.1
      database: 0
      port: 6379

  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: gseek
    secretKey: gseek
    bucketName: gseek

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  jmx:
    server:
