server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    include:
      alipay

  datasource:
    url: jdbc:mysql://localhost:3306/gseek?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: gseek
    password: Gseek_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database:
        db1: 0
        db2: 1
      host: 127.0.0.1
      port: 6379
      pool:
        max-active: 100
        max-idle: 3
        min-idle: 0
        max-wait: -1

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: gseek
    password: gseek
    virtual-host: GseekHost
    relay_host: GseekHost

logging:
  level:
    root: info

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: gseek
  secretKey: gseek123456
  bucketName: gseek





# 自定义参数
custom:
  # aes加密key值，在PasswordUtil#init中用到
  encryptKey: test1encrypt2key
  # 平台抽成后卖家获得多少钱
  agreementFee: 0.7
  # 主机名
  localhost: 118.178.243.30

