server:
  port: 8080

spring:
  profiles:
    include:
      alipay

  datasource:
    url: jdbc:mysql://localhost:3306/gseek?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: gseek
    password: gseek
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379

  rabbitmq:
    host: 127.0.0.1
    port: 15674
    username: gseek
    password: gseek
    virtual-host: GseekHost
    relay_host: GseekHost

logging:
  level:
    root: info

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: gseek
  secretKey: gseek123456
  bucketName: gseek





# 自定义参数
custom:
  # aes加密key值，在PasswordUtil#init中用到
  encryptKey: "test1encrypt2key"

